version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app     # live reload for dev
      - /app/node_modules   # prevent overwriting container modules
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app      # live reload for dev
      - /app/__pycache__    # prevent overwrite of cache
    environment:
      DATABASE_URL: postgresql://taskflow:taskflow@db:5432/taskflow
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --reload  # dev mode

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data     # persist DB
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
